using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Documents;
using Avalonia.Media;

namespace Prompuff.App.Controls;

/// <summary>
/// A Lucide icon drawn as strokes in the current foreground color. Geometry comes from
/// <see cref="IconData"/>, generated by <c>scripts/generate-icons.py</c>.
/// </summary>
public sealed class Icon : Control
{
    public static readonly StyledProperty<string?> KindProperty =
        AvaloniaProperty.Register<Icon, string?>(nameof(Kind));

    public static readonly StyledProperty<double> SizeProperty =
        AvaloniaProperty.Register<Icon, double>(nameof(Size), 14);

    /// <summary>Stroke width in device-independent pixels, whatever the icon size.</summary>
    public static readonly StyledProperty<double> StrokeWidthProperty =
        AvaloniaProperty.Register<Icon, double>(nameof(StrokeWidth), 1.6);

    public static readonly StyledProperty<bool> IsFilledProperty =
        AvaloniaProperty.Register<Icon, bool>(nameof(IsFilled));

    public static readonly StyledProperty<IBrush?> ForegroundProperty =
        TextElement.ForegroundProperty.AddOwner<Icon>();

    private static readonly Dictionary<string, Geometry> Cache = new(StringComparer.Ordinal);

    static Icon()
    {
        AffectsRender<Icon>(KindProperty, StrokeWidthProperty, IsFilledProperty, ForegroundProperty);
        AffectsMeasure<Icon>(SizeProperty);
    }

    public string? Kind
    {
        get => GetValue(KindProperty);
        set => SetValue(KindProperty, value);
    }

    public double Size
    {
        get => GetValue(SizeProperty);
        set => SetValue(SizeProperty, value);
    }

    public double StrokeWidth
    {
        get => GetValue(StrokeWidthProperty);
        set => SetValue(StrokeWidthProperty, value);
    }

    public bool IsFilled
    {
        get => GetValue(IsFilledProperty);
        set => SetValue(IsFilledProperty, value);
    }

    public IBrush? Foreground
    {
        get => GetValue(ForegroundProperty);
        set => SetValue(ForegroundProperty, value);
    }

    protected override Size MeasureOverride(Size availableSize) => new(Size, Size);

    public override void Render(DrawingContext context)
    {
        if (Kind is null || Foreground is not { } brush || GetGeometry(Kind) is not { } geometry)
        {
            return;
        }

        var scale = Size / 24d;
        var offset = new Point((Bounds.Width - Size) / 2, (Bounds.Height - Size) / 2);
        using (context.PushTransform(Matrix.CreateScale(scale, scale) * Matrix.CreateTranslation(offset.X, offset.Y)))
        {
            var pen = new Pen(brush, StrokeWidth / scale, lineCap: PenLineCap.Round, lineJoin: PenLineJoin.Round);
            context.DrawGeometry(IsFilled ? brush : null, pen, geometry);
        }
    }

    private static Geometry? GetGeometry(string kind)
    {
        if (Cache.TryGetValue(kind, out var cached))
        {
            return cached;
        }

        if (!IconData.Paths.TryGetValue(kind, out var data))
        {
            return null;
        }

        var geometry = StreamGeometry.Parse(data);
        Cache[kind] = geometry;
        return geometry;
    }
}
