<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Prompuff.Application\Prompuff.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Velopack" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Prompuff.Infrastructure.Tests" />
    <InternalsVisibleTo Include="Prompuff.Performance.Tests" />
  </ItemGroup>
</Project>
